In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import rdkit, rdkit.Chem
import numpy as np
import tensorflow as tf

import data

In [ ]:
df = pd.read_csv("https://github.com/whitead/dmol-book/raw/main/data/curated-solubility-dataset.csv")
df

,ID,Name,InChI,InChIKey,SMILES,Solubility,SD,Ocurrences,Group,MolWt,...,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",InChI=1S/C21H46N.BrH/c1-5-6-7-8-9-10-11-12-13-...,SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,0.000000,1,G1,392.510,...,17.0,142.0,0.0,0.0,0.0,0.0,0.00,158.520601,0.000000e+00,210.377334
1,A-4,Benzo[cd]indol-2(1H)-one,InChI=1S/C11H7NO/c13-11-8-5-1-3-7-4-2-6-9(12-1...,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,0.000000,1,G1,169.183,...,0.0,62.0,2.0,0.0,1.0,3.0,29.10,75.183563,2.582996e+00,511.229248
2,A-5,4-chlorobenzaldehyde,InChI=1S/C7H5ClO/c8-7-3-1-6(5-9)2-4-7/h1-5H,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,0.000000,1,G1,140.569,...,1.0,46.0,1.0,0.0,0.0,1.0,17.07,58.261134,3.009782e+00,202.661065
3,A-8,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",InChI=1S/2C23H22O3.Zn/c2*1-15(17-9-5-3-6-10-17...,XTUPUYCJWKHGSW-UHFFFAOYSA-L,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,0.000000,1,G1,756.226,...,10.0,264.0,6.0,0.0,0.0,6.0,120.72,323.755434,2.322963e-07,1964.648666
4,A-9,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,InChI=1S/C25H30N2O4/c1-5-20(26(10-22-14-28-22)...,FAUAZXVRLVIARB-UHFFFAOYSA-N,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,0.000000,1,G1,422.525,...,12.0,164.0,2.0,4.0,4.0,6.0,56.60,183.183268,1.084427e+00,769.899934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,I-84,tetracaine,InChI=1S/C15H24N2O2/c1-4-5-10-16-14-8-6-13(7-9...,GKCBAIGFKIBETG-UHFFFAOYSA-N,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,0.000000,1,G1,264.369,...,8.0,106.0,1.0,0.0,0.0,1.0,41.57,115.300645,2.394548e+00,374.236893
9978,I-85,tetracycline,InChI=1S/C22H24N2O8/c1-21(31)8-5-4-6-11(25)12(...,OFVLGDICTFRJMM-WESIUVDSSA-N,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,0.000000,1,G1,444.440,...,2.0,170.0,1.0,0.0,3.0,4.0,181.62,182.429237,2.047922e+00,1148.584975
9979,I-86,thymol,InChI=1S/C10H14O/c1-7(2)9-5-4-8(3)6-10(9)11/h4...,MGSRCZKZVOBKFT-UHFFFAOYSA-N,c1(cc(ccc1C(C)C)C)O,-2.190000,0.019222,3,G5,150.221,...,1.0,60.0,1.0,0.0,0.0,1.0,20.23,67.685405,3.092720e+00,251.049732
9980,I-93,verapamil,"InChI=1S/C27H38N2O4/c1-20(2)27(19-28,22-10-12-...",SGTNSNPWRIOYBX-UHFFFAOYSA-N,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,0.000000,1,G1,454.611,...,13.0,180.0,2.0,0.0,0.0,2.0,63.95,198.569223,2.023333e+00,938.203977
9981,I-94,warfarin,InChI=1S/C19H16O4/c1-12(20)11-15(13-7-3-2-4-8-...,PJVWKTKQMONHTI-UHFFFAOYSA-N,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,0.450506,3,G5,308.333,...,4.0,116.0,3.0,0.0,0.0,3.0,67.51,132.552025,2.258072e+00,909.550973

define features

In [ ]:
X_start = list(df.columns).index("MolWt")
X_names = df.columns[X_start:]
X = df[X_names]
y = df['Solubility']

linear regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

lr = LinearRegression()
lr.fit(X = X_train, y = y_train)

y_pred = lr.predict(X_test)
print("R2 score: " + str(r2_score(y_test,y_pred)))

R2 score: 0.514909225330791

ANN

In [ ]:
model = tf.keras.models.Sequential([
tf.keras.Input(shape=(17,)),
tf.keras.layers.Dense(20, activation='relu'),
tf.keras.layers.Dense(20, activation='relu'),
tf.keras.layers.Dense(1)
])

tf.keras.utils.plot_model(model,
show_shapes=True,
show_dtype=True,
show_layer_names=True,
rankdir='TB',
expand_nested=True,
dpi=64,
show_layer_activations=True,
show_trainable=True
)

model.compile(optimizer='adam', loss='mse')

model.fit(np.array(X_train), np.array(y_train), batch_size = 16, epochs = 50)

r2_metric = tf.keras.metrics.R2Score()

r2_metric.update_state(np.array(y_test), model.predict(np.array(X_test)))

print("R2 Score:", r2_metric.result().numpy())

Epoch 1/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 7.6833
Epoch 2/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.7134
Epoch 3/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 2.1593
Epoch 4/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.0316
Epoch 5/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 2.0120
Epoch 6/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.8213
Epoch 7/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.8828
Epoch 8/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.7078
Epoch 9/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.7566
Epoch 10/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.6020
Epoch 11/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.6911
Epoch 12/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.6806
Epoch 13/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.5525
Epoch 14/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.6225
Epoch 15/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5807
Epoch 16/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.6298
Epoch 17/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5322
Epoch 18/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5605
Epoch 19/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5125
Epoch 20/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4760
Epoch 21/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.4105
Epoch 22/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.5333
Epoch 23/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.5168
Epoch 24/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4441
Epoch 25/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.5007
Epoch 26/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.4042
Epoch 27/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4600
Epoch 28/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4830
Epoch 29/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4652
Epoch 30/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4809
Epoch 31/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.4818
Epoch 32/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1.3453
Epoch 33/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.3350
Epoch 34/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3547
Epoch 35/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3798
Epoch 36/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4003
Epoch 37/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.3788
Epoch 38/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3671
Epoch 39/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4488
Epoch 40/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.3920
Epoch 41/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4008
Epoch 42/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.3502
Epoch 43/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2915
Epoch 44/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.3637
Epoch 45/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3539
Epoch 46/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3492
Epoch 47/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2935
Epoch 48/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.4776
Epoch 49/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3076
Epoch 50/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.3578
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step
R2 Score: 0.7578839

do the same thing, but use rdkit to featurize the molecules instead

In [ ]:
mols = pd.read_csv("https://github.com/whitead/dmol-book/raw/main/data/curated-solubility-dataset.csv")
molecules = [rdkit.Chem.MolFromSmiles(smi) for smi in mols.SMILES]

valid_mol_idx = [bool(m) for m in molecules]
valid_mols = [m for m in molecules if m]
len(valid_mols)

[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] Explicit valence for atom # 5 N, 4, is greater than permitted
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] Explicit valence for atom # 5 N, 4, is greater than permitted
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors
[09:54:00] WARNING: not removing hydrogen atom without neighbors

9980

In [ ]:
from rdkit.Chem import Descriptors

vals = [Descriptors.CalcMolDescriptors(x) for x in valid_mols]
X = pd.DataFrame(vals)
X

[10:57:15] WARNING: not removing hydrogen atom without neighbors
[10:57:16] WARNING: not removing hydrogen atom without neighbors
[10:57:16] WARNING: not removing hydrogen atom without neighbors
[10:57:18] WARNING: not removing hydrogen atom without neighbors
[10:57:18] WARNING: not removing hydrogen atom without neighbors
[10:57:19] WARNING: not removing hydrogen atom without neighbors
[10:57:19] WARNING: not removing hydrogen atom without neighbors
[10:57:19] WARNING: not removing hydrogen atom without neighbors
[10:57:19] WARNING: not removing hydrogen atom without neighbors
[10:57:20] WARNING: not removing hydrogen atom without neighbors
[10:57:20] WARNING: not removing hydrogen atom without neighbors
[10:57:20] WARNING: not removing hydrogen atom without neighbors
[10:57:30] WARNING: not removing hydrogen atom without neighbors
[10:57:30] WARNING: not removing hydrogen atom without neighbors
[10:57:30] WARNING: not removing hydrogen atom without neighbors
[10:57:30] WARNING: not removing hydrogen atom without neighbors
[10:57:31] WARNING: not removing hydrogen atom without neighbors
[10:57:31] WARNING: not removing hydrogen atom without neighbors
[10:57:31] WARNING: not removing hydrogen atom without neighbors
[10:57:31] WARNING: not removing hydrogen atom without neighbors
[10:57:32] WARNING: not removing hydrogen atom without neighbors
[10:57:32] WARNING: not removing hydrogen atom without neighbors
[10:57:33] WARNING: not removing hydrogen atom without neighbors
[10:57:33] WARNING: not removing hydrogen atom without neighbors
[10:57:34] WARNING: not removing hydrogen atom without neighbors
[10:57:34] WARNING: not removing hydrogen atom without neighbors
[10:57:34] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:35] WARNING: not removing hydrogen atom without neighbors
[10:57:36] WARNING: not removing hydrogen atom without neighbors
[10:57:37] WARNING: not removing hydrogen atom without neighbors
[10:57:37] WARNING: not removing hydrogen atom without neighbors
[10:57:37] WARNING: not removing hydrogen atom without neighbors
[10:57:37] WARNING: not removing hydrogen atom without neighbors
[10:57:38] WARNING: not removing hydrogen atom without neighbors
[10:57:38] WARNING: not removing hydrogen atom without neighbors
[10:57:38] WARNING: not removing hydrogen atom without neighbors
[10:57:39] WARNING: not removing hydrogen atom without neighbors
[10:57:39] WARNING: not removing hydrogen atom without neighbors
[10:57:41] WARNING: not removing hydrogen atom without neighbors
[10:57:41] WARNING: not removing hydrogen atom without neighbors
[10:57:42] WARNING: not removing hydrogen atom without neighbors
[10:57:42] WARNING: not removing hydrogen atom without neighbors
[10:57:43] WARNING: not removing hydrogen atom without neighbors
[10:57:43] WARNING: not removing hydrogen atom without neighbors
[10:57:43] WARNING: not removing hydrogen atom without neighbors
[10:57:43] WARNING: not removing hydrogen atom without neighbors
[10:57:44] WARNING: not removing hydrogen atom without neighbors
[10:57:48] WARNING: not removing hydrogen atom without neighbors
[10:57:48] WARNING: not removing hydrogen atom without neighbors
[10:57:48] WARNING: not removing hydrogen atom without neighbors
[10:57:50] WARNING: not removing hydrogen atom without neighbors
[10:57:50] WARNING: not removing hydrogen atom without neighbors
[10:57:50] WARNING: not removing hydrogen atom without neighbors
[10:57:52] WARNING: not removing hydrogen atom without neighbors
[10:57:54] WARNING: not removing hydrogen atom without neighbors
[10:57:56] WARNING: not removing hydrogen atom without neighbors
[10:57:58] WARNING: not removing hydrogen atom without neighbors
[10:58:01] WARNING: not removing hydrogen atom without neighbors
[10:58:01] WARNING: not removing hydrogen atom without neighbors

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,2.296832,2.296832,0.000000,0.000000,0.259676,11.478261,392.510,346.142,391.281363,142,...,0,0,0,0,0,0,0,0,15,0
1,11.435093,11.435093,0.006296,0.006296,0.644215,13.384615,169.183,162.127,169.052764,62,...,0,0,0,0,0,0,0,0,0,0
2,10.074698,10.074698,0.652222,0.652222,0.546650,9.000000,140.569,135.529,140.002892,46,...,0,0,0,0,0,0,0,0,0,0
3,11.573312,11.573312,0.000000,-1.369330,0.136407,12.905660,756.226,713.890,754.227281,264,...,0,0,0,0,0,0,0,0,0,0
4,5.440876,5.440876,0.383760,0.383760,0.490100,27.612903,422.525,392.285,422.220557,164,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9975,11.736681,11.736681,0.262076,-0.262076,0.578688,10.526316,264.369,240.177,264.183778,106,...,0,0,0,0,0,0,0,0,1,0
9976,13.313695,13.313695,0.134831,-2.745034,0.336110,34.375000,444.440,420.248,444.153266,170,...,0,0,0,0,0,0,0,0,0,0
9977,9.461759,9.461759,0.398704,0.398704,0.652274,10.545455,150.221,136.109,150.104465,60,...,0,0,0,0,0,0,0,0,0,0
9978,10.242105,10.242105,0.164510,-0.579622,0.419905,12.848485,454.611,416.307,454.283158,180,...,0,0,0,0,0,0,0,0,0,0
9979,12.412307,12.412307,0.064063,-0.614534,0.747626,12.217391,308.333,292.205,308.104859,116,...,0,0,0,0,0,0,0,0,0,0

use descriptors to train model instead

In [ ]:
X.dropna(inplace = True, axis = 1)
len(X), len(X.columns)

X = np.clip(X.values.astype(np.float64), -1000, 1000)
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

model = tf.keras.models.Sequential([
tf.keras.Input(shape=(205,)),
tf.keras.layers.Dense(50, activation='relu'),
tf.keras.layers.Dense(50, activation='relu'),
tf.keras.layers.Dense(50, activation='relu'),
tf.keras.layers.Dense(1)
])

tf.keras.utils.plot_model(model,
show_shapes=True,
show_dtype=True,
show_layer_names=True,
rankdir='TB',
expand_nested=True,
dpi=64,
show_layer_activations=True,
show_trainable=True
)

model.compile(optimizer='adam', loss='mse')

model.fit(np.array(X_train), np.array(y_train), batch_size = 16, epochs = 50)

r2_metric = tf.keras.metrics.R2Score()

r2_metric.update_state(np.array(y_test), model.predict(np.array(X_test)))

print("R2 Score:", r2_metric.result().numpy())

Epoch 1/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 5.4938
Epoch 2/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.5251
Epoch 3/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.1588
Epoch 4/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.1490
Epoch 5/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.9451
Epoch 6/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.9377
Epoch 7/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.8384
Epoch 8/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7986
Epoch 9/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7936
Epoch 10/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7357
Epoch 11/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7444
Epoch 12/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7500
Epoch 13/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.7690
Epoch 14/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.6664
Epoch 15/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.6180
Epoch 16/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.5270
Epoch 17/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.5456
Epoch 18/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.5756
Epoch 19/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5384
Epoch 20/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.5152
Epoch 21/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4896
Epoch 22/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.5224
Epoch 23/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4657
Epoch 24/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4638
Epoch 25/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.5039
Epoch 26/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4649
Epoch 27/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4300
Epoch 28/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4514
Epoch 29/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4530
Epoch 30/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4252
Epoch 31/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4014
Epoch 32/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3856
Epoch 33/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3903
Epoch 34/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3622
Epoch 35/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3758
Epoch 36/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3601
Epoch 37/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3797
Epoch 38/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3573
Epoch 39/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3286
Epoch 40/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3455
Epoch 41/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3445
Epoch 42/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3166
Epoch 43/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3303
Epoch 44/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3574
Epoch 45/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2680
Epoch 46/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3231
Epoch 47/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3193
Epoch 48/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3073
Epoch 49/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2831
Epoch 50/50
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3368
103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
R2 Score: 0.75203806

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step

0.7520380094871111